### ISSUE TITLE
The view function for 'flask_saml2_sp.acs' did not return a valid response.

### ISSUE THREAD

**Issue by jl2035** [timheap/flask-saml2#34]
I'm using flask_saml2 library for my SP and as an IDP I'm using Wordpress with miniorange plugin.

SP correctly redirects to IDP login, but after a successful login into wordpress the request is being made to my SP URL /saml/acs, but I get the following error.

```
192.168.50.35 - - [11/Feb/2022 04:57:37] "POST /saml/acs/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/root/sp/venv/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/sp/venv/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/root/sp/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/sp/venv/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "/root/sp/venv/lib/python3.8/site-packages/flask/app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "/root/sp/venv/lib/python3.8/site-packages/flask/app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'flask_saml2_sp.acs' did not return a valid response. The function either returned None or ended without a return statement.
```

Can somebody point me to the relevant peace of code? Where can I find this view/function?

**Comment by jl2035** [comment]
This was fixed by configuring the correct URLs on the SP side.

**Comment by Gonzalopachecotena** [comment]
Hi, I have the same error and I don´t know how to solve it.
Can you explain me your solution with more detail please?

**Comment by jl2035** [comment]
@Gonzalopachecotena honestly I don't remember, but I would recommend you double triple check the URLs in the saml configuration on the SP side.

**Comment by ayancey** [comment]
In my case, "issuer" / "entity_id" was incorrect.
